language: python

# These two lines give us a beefier VM with ~7Gb of memory instead of 4.  This
# helps ensure that Z3 builds without errors.
# See: https://docs.travis-ci.com/user/reference/overview/
sudo: required
dist: trusty

cache: pip
python:
  - "3.5"
addons:
  apt:
    update: true
    packages:
      - python3-flake8
install:
  - pip install .
script:
  - "flake8
      --count
      --select=E901,E999,F821,F822,F823,W2,W3,E703,E114,W191
      --show-source
      $(find cozy tests -name '*.py' -not -name 'parsetab.py')"
  - python -m unittest -vb tests/*.py
